### ISSUE TITLE
Make `lint` the default command

### ISSUE THREAD

**Issue by sobolevn** [life4/flakehell#16]
```
» flakehell
baseline  | Run patched flake8 against the code.
codes     | Show available codes and messages for given plugin.
lint      | Run patched flake8 against the code.
missed    | Show patterns from the config that has no matched plugin installed.
plugins   | Show all installed plugins, their codes prefix, and matched rules from config.
No command provided
```

A lot of people might expect the same behavior from `flakehell` that they are used to with` flake8`. Given that `flakehell lint` is compatible with `flake8` it might be a good idea to run it by default. This will the adoption easier just by swapping the binary.

**Comment by orsinium** [comment]
I thought about it. All multi-command tools provide commands list and short descriprion if no arguments specified. When I type some command name without args, it's the start of my journey, and I want to see, what it can do and how it works. Type `pipenv`, `poetry`, `mypy`, and you'll get the same behavior.

> A lot of people might expect the same behavior from flakehell that they are used to with flake8. 

This expectation will be broken, but the user will get a guide on how to use it instead. Flakehell intended to be used always with the config. So, `lint` isn't your first command. Your journey starts fron the environment discovery: `plugins`, `missed`, and `codes` (see README for the workflow).

> This will the adoption easier just by swapping the binary.

We'll provide `patch` command to patch `flake8` binary and entrypoint to use `flakehell lint` instead (#19). This entrypoint also will use default formatter (because IDE plugins parse it).
