### ISSUE TITLE
pylint plugin is extremely slow

### ISSUE THREAD

**Issue by auscompgeek** [life4/flakehell#42]

**Comment by orsinium** [comment]
This is because pylint is slow. Pylint uses [astroid](http://pylint.pycqa.org/projects/astroid/en/latest/) instead of AST that does lookup and inference, and it's a really difficult job for a dynamic programming language. I can't do anything here, sorry. You can open an issue in the pylint itself if you have ideas on how to make it faster.

**Comment by auscompgeek** [comment]
Well sure, but pylint proper actually gives me results as it processes files. With this, I sit for a good minute when I lint my projects with no output.

**Comment by orsinium** [comment]
Flake8 does the same. Linting goes before report formatting.
